### ISSUE TITLE
Error with Meta function

### ISSUE THREAD

**Issue by laralps** [xaviermouy/PAMGuide-modifications#1]
Hello to all!

I was unsure if this was the best place to post this question, so if you have a better place to discuss PAMGuide, please let me know.
I am having trouble running the function Meta in R. I need to analyze 1 month of continuous data recorded in an aquatic environment at 96khz with SoundTrap as 10 minute files. I want to run PSD analysis using an averaging factor of 10. I used the following code: 

```
Meta(atype = "PSD", 
     plottype = "Stats", 
     envi = "Wat",  
     r = 50, 
     winname = 'Hann',
     calib = 1, 
     ctype = "EE", 
     Si= -175.9, # calibration value from SoundTrap
     linlog = "Log", 
     lcut = 20, 
     welch = 10,  # for 5s time resolution
     timestring = "6690.%y%m%d%H%M%S.wav", 
     outwrite = 1, #
     outdir = "D:/PBS_Monitoramento acústico/Analises/PSD_resultados/Dep01_220502-220623/Dep01_S01_ST6690/2205"
     )
```

The files are being recognized but i get the following error message:

```
No. of WAV files in selected directory:  4239 
Time stamp start time:  2022-05-02 13:34:14 
Analysis type: PSD 
Plot type: None 
Underwater measurement
Hydrophone sensitivity: -36 dB re 1 V/uPa
Preamplifier gain: 0 dB
ADC peak voltage: 1.414 V
Time segment length: 96000 samples = 1 s
Window function: Hann 
Window overlap: 50 %
System sensitivity correction factor, S =  -39.0  dB
Error in as.POSIXlt.character(x, tz, ...) : 
   character string is not in a standard unambiguous format
In addition: Warning message:
 Error in as.POSIXlt.character(x, tz, ...) : 
 character string is not in a standard unambiguous format
```

What can be happening? Is there a problem with the filenames format?

Thanks for any support,

**Comment by laralps** [comment]
A different problem I'm having is that I can select multiple files for Viewer plotting through MatLab (although the figures are not being generated after), but in Viewer through R I can still select only one file at a time.

**Comment by xaviermouy** [comment]
Hi @laralps, unfortunately I have never used the R version of PAMGuide, so can't really help. However, I would suggest to ask Nathan Merchant who is the author of PAMGuide. I would also recommend posting your question on the Bioacoustics Stack Exchange page: https://bioacoustics.stackexchange.com/. Someone will likely be able to help  you there.

Good luck,
Xavier
